import Head from 'next/head'
import type { NextPage } from 'next'
import ProductDetails from 'components/ProductDetails'
import AddToCart from 'components/AddToCart'
import { styled } from 'stitches.config'
import ImageSlider from 'components/ImageSlider'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Frontend Mentor | E-commerce product page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Main>
        <ImageSlider />
        <div>
          <ProductDetails />
          <AddToCart />
        </div>
      </Main>
    </div>
  )
}

const Main = styled('main', {
  maxWidth: '800px',
  margin: 'auto',

  '@bp1': {
    maxWidth: '1264px',
    display: 'grid',
    gridTemplateColumns: 'minmax(auto, 506px) minmax(auto, 506px)',
    justifyContent: 'space-between',
    padding: '56px',
  },
})

export default Home
