import Head from 'next/head'
import type { NextPage } from 'next'
import ProductDetails from 'components/ProductDetails'
import AddToCart from 'components/AddToCart'
import { styled } from 'stitches.config'
import ImageSlider from 'components/ImageSlider'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Frontend Mentor | E-commerce product page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Main>
        <ImageSlider />
        <ProductDetails />
        <AddToCart />
      </Main>
    </div>
  )
}

const Main = styled('main', {
  maxWidth: '800px',
  margin: 'auto',
  padding: '0 1rem'
})

export default Home
