import { useState, useEffect } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import ProductDetails from 'components/ProductDetails'
import AddToCart from 'components/AddToCart'
import { styled } from 'stitches.config'
import ImageSlider from 'components/ImageSlider'
import ClientOnlyPortal from 'utils/ClientOnlyPortal'

const Home: NextPage = () => {
  const [isModalOpen, setIsModalOpen] = useState(false)

  useEffect(() => {
    if (isModalOpen) document.body.style.overflowY = 'hidden'
    if (!isModalOpen) document.body.style.overflowY = 'revert'
  }, [isModalOpen])

  return (
    <>
      <Head>
        <title>Frontend Mentor | E-commerce product page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Main>
        {isModalOpen && (
          <ClientOnlyPortal selector='#modal'>
            <DesktopOnly>
              <Modal className='modal-overlay'>
                <ImageSlider isModal={true} {...{ setIsModalOpen }} />
              </Modal>
            </DesktopOnly>
          </ClientOnlyPortal>
        )}
        <ImageSlider {...{ isModalOpen, setIsModalOpen }} />
        <div>
          <ProductDetails />
          <AddToCart />
        </div>
      </Main>
    </>
  )
}

const Main = styled('main', {
  maxWidth: '800px',
  margin: 'auto',

  '@bp1': {
    maxWidth: '1015px',
    display: 'grid',
    gap: '65px',
    gridTemplateColumns: 'minmax(450px, 506px) minmax(auto, 506px)',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: '-2px',
    marginBottom: '60px',

    '& > div': {
      marginTop: '90px',
    },
  },
})

const DesktopOnly = styled('div', {
  display: 'none',
  '@bp1': {
    display: 'revert',
  },
})

const Modal = styled('div', {
  backgroundColor: '$blackA1',
  position: 'fixed',
  inset: '0 0 0 0',
  overflowY: 'auto',

  '& > div': {
    position: 'absolute',
    width: '500px',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
  },
})

export default Home
